const PathConstants = {
    HOME: "/",
    ABOUTPAGE: "/about-page",
    SERVICESPAGE: "/services-page",
    PROJECTPAGE: "/project-page",
    CONTACTPAGE: "/contact-page",
    BLOGPAGE: "/blog-page",
    TEAMPAGE: "/team-page",
    PRICINGPAGE: "/pricing-page",
    LIECENSESPAGE: "/liecenses-page",
    SEATRANSPORTPAGE: "/sea-transport-services-page",
    WAREHOUSINGPAGE: "/warehousing-services-page",
    AIRFRIGHTPAGE: "/air-fright-services-page",
    LOCALSHIPPINGPAGE: "/local-shipping-page",
    PROJECTDETAILS01: "/project-details01-page",
    PROJECTDETAILS02: "/project-details02-page",
    PROJECTDETAILS03: "/project-details03-page",
    PROJECTDETAILS04: "/project-details04-page",
    PROJECTDETAILS05: "/project-details05-page",
    PROJECTDETAILS06: "/project-details06-page",
}
export default PathConstants;