export const blogPosts = [{
    id: "blPost01",
    imgSrc: "/blog-image01.jpeg",
    imgAlt: "image",
    postData: "08 March",
    rubric: "Wharehouse Transportation",
    linkTo: "",
    title: "Inland freight a worthy solution for your business",
    text: "Duis semper lacus scelerisque, aliquam leo quis, porttitor leo. Etiam lobortis dapibus libero vel porttitor. Nulla tempor elit nec attempus.Phasellus at quam hendrerit semper David Warner nunc. Morbi quis justo velit. Duis semper lacus scelerisque, aliquam leo quis, porttitor leo Fusce lectus ex pretium...",
}, {
    id: "blPost02",
    imgSrc: "/blog-image02.jpeg",
    imgAlt: "image",
    postData: "12 March",
    rubric: "Sea Transport Services",
    linkTo: "",
    title: "How technology can help redraw the supply chain map",
    text: "Duis semper lacus scelerisque, aliquam leo quis, porttitor leo. Etiam lobortis dapibus libero vel porttitor. Nulla tempor elit nec attempus.Phasellus at quam hendrerit semper David Warner nunc. Morbi quis justo velit. Duis semper lacus scelerisque, aliquam leo quis, porttitor leo Fusce lectus ex pretium...",
}, {
    id: "blPost03",
    imgSrc: "/blog-image03.jpeg",
    imgAlt: "image",
    postData: "25 March",
    rubric: "Care for Environment",
    linkTo: "",
    title: "Five things you should have ready for your broker",
    text: "Duis semper lacus scelerisque, aliquam leo quis, porttitor leo. Etiam lobortis dapibus libero vel porttitor. Nulla tempor elit nec attempus.Phasellus at quam hendrerit semper David Warner nunc. Morbi quis justo velit. Duis semper lacus scelerisque, aliquam leo quis, porttitor leo Fusce lectus ex pretium...",
},{
    id: "blPost04",
    imgSrc: "/blog-image04.jpeg",
    imgAlt: "image",
    postData: "28 March",
    rubric: "Local Shipping Services",
    linkTo: "", 
    title: "Four simple tips for becoming a healthier truck driver",
    text: "Duis semper lacus scelerisque, aliquam leo quis, porttitor leo. Etiam lobortis dapibus libero vel porttitor. Nulla tempor elit nec attempus.Phasellus at quam hendrerit semper David Warner nunc. Morbi quis justo velit. Duis semper lacus scelerisque, aliquam leo quis, porttitor leo Fusce lectus ex pretium...",
}, {
    id: "blPost05",
    imgSrc: "/blog-image05.jpeg",
    imgAlt: "image",
    postData: "30 March",
    rubric: "Air Cargo Transportation",
    linkTo: "", 
    title: "What is the role of a logistics operations manager",
    text: "Duis semper lacus scelerisque, aliquam leo quis, porttitor leo. Etiam lobortis dapibus libero vel porttitor. Nulla tempor elit nec attempus.Phasellus at quam hendrerit semper David Warner nunc. Morbi quis justo velit. Duis semper lacus scelerisque, aliquam leo quis, porttitor leo Fusce lectus ex pretium...",
}];