export const overviewTabs = [{
    id: "ovTab01",
    buttonText: "Experience",
    text: "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem quia voluptassit. Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem quia voluptassit...",
    imageSrc: "/overview-image01.jpeg",
    imageAlt: "Image",
    buttonLinkText: "Learn More",
    linkTo: "/blog-page",
}, {
    id: "ovTab02", 
    buttonText: "Reliability",
    text: "Unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem quia voluptassit. Unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem quia voluptassit...",
    imageSrc: "/overview-image02.jpeg",
    imageAlt: "Image",
    buttonLinkText: "Learn More",
    linkTo: "/blog-page",
}, {
    id: "ovTab03", 
    buttonText: "Partnership",
    text: "Accusantium doloremque laudantium, totam rem aperiam eaque ipsa,sed ut perspiciatis, unde omnis iste natus error sit voluptatem  quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt. Explicabo.rem aperiam eaque ipsa quae ab illo. Accusantium doloremque laudantium, totam rem aperiam eaque ipsa,sed ut perspiciatis, unde omnis iste natus error sit voluptatem  quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt. Explicabo.rem aperiam eaque ipsa quae ab illo. Accusantium doloremque laudantium, totam rem aperiam eaque ipsa,sed ut perspiciatis, unde omnis iste natus error sit voluptatem  quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt. Explicabo.rem aperiam eaque ipsa quae ab illo...",
    imageSrc: "/overview-image03.jpg",
    imageAlt: "Image",
    buttonLinkText: "Learn More",
    linkTo: "/blog-page",
}];