export const testimonials = [{
    id: "teS01",
    color: "#F4F4F4",
    imageSrc: "/testimonial-user-image01.png",
    userName: "Kathleen Smith",
    userPosition: "Fuel Company",
    iconSrc: "/testimonial-icon.png",
    text: "Leverage agile frameworks to provide a robust synopsis for strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.",
    starRating: "/stars-rating-image.png",
}, {
    id: "teS02",
    color: "#e3e4ea",
    imageSrc: "/testimonial-user-image03.png",
    userName: "Layla Robinson",
    userPosition: "Flower Shop",
    iconSrc: "/testimonial-icon.png",
    text: "Leverage agile frameworks to provide a robust synopsis for strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.",
    starRating: "/stars-rating-image.png",
}, {
    id: "teS03",
    color: "#F4F4F4",
    imageSrc: "/testimonial-user-image02.png",
    userName: "John Martin",
    userPosition: "Restoration Company",
    iconSrc: "/testimonial-icon.png",
    text: "Leverage agile frameworks to provide a robust synopsis for strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.",
    starRating: "/stars-rating-image.png",
}, {
    id: "teS04",
    color: "#e3e4ea",
    imageSrc: "/testimonial-user-image04.png",
    userName: "Madison Clark",
    userPosition: "Attelier",
    iconSrc: "/testimonial-icon.png",
    text: "Leverage agile frameworks to provide a robust synopsis for strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment.",
    starRating: "/stars-rating-image.png",
}];